-- Walton Trailers website — Supabase schema.
-- Run this once in the Supabase SQL editor after creating the project.
--
-- Two public-write, owner-read tables:
--   trailer_registrations  ← /register.html
--   dealer_inquiries       ← /become-a-dealer.html
--
-- Security model:
--   - Anonymous users can INSERT (so unauthenticated visitors can submit).
--   - Anonymous users CANNOT SELECT, UPDATE, or DELETE.
--   - Only authenticated users (Taylor, via the Supabase dashboard or
--     a future admin app) can read rows.

create table if not exists public.trailer_registrations (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  first_name    text not null,
  last_name     text not null,
  email         text not null,
  phone         text,
  address       text,
  state         text,
  zip           text,
  country       text default 'United States',
  purchase_date date,
  vin           text,
  model         text,
  dealer        text,
  proof_url     text,         -- Optional URL to the proof-of-purchase doc once uploaded to storage.
  source        text default 'register.html',
  user_agent    text,
  notes         text
);

create table if not exists public.dealer_inquiries (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  first_name      text not null,
  last_name       text not null,
  email           text not null,
  phone           text not null,
  dealer_name     text not null,
  address         text,
  city            text,
  state           text,
  zip             text,
  country         text default 'United States',
  years_in_business text,
  parts_program   text,        -- "yes"/"no" radio
  service_program text,        -- "yes"/"no" radio
  trailer_types   text[],      -- categories they want to carry
  current_brands  text,
  message         text,
  source          text default 'become-a-dealer.html',
  user_agent      text,
  notes           text
);

-- ── Row Level Security ─────────────────────────────────────────────
alter table public.trailer_registrations enable row level security;
alter table public.dealer_inquiries enable row level security;

-- Anyone (the anon role) can insert a row. Nothing else.
drop policy if exists "anon insert trailer_registrations" on public.trailer_registrations;
create policy "anon insert trailer_registrations"
  on public.trailer_registrations
  for insert
  to anon
  with check (true);

drop policy if exists "anon insert dealer_inquiries" on public.dealer_inquiries;
create policy "anon insert dealer_inquiries"
  on public.dealer_inquiries
  for insert
  to anon
  with check (true);

-- Authenticated users (Taylor + future admin app) can read everything.
drop policy if exists "auth read trailer_registrations" on public.trailer_registrations;
create policy "auth read trailer_registrations"
  on public.trailer_registrations
  for select
  to authenticated
  using (true);

drop policy if exists "auth read dealer_inquiries" on public.dealer_inquiries;
create policy "auth read dealer_inquiries"
  on public.dealer_inquiries
  for select
  to authenticated
  using (true);

-- ── Storage bucket for proof-of-purchase uploads ───────────────────
-- Private bucket — anyone can upload, only authenticated users can
-- read the files via signed URLs from the dashboard / future admin UI.
insert into storage.buckets (id, name, public)
values ('proof-of-purchase', 'proof-of-purchase', false)
on conflict (id) do nothing;

drop policy if exists "anon upload proof" on storage.objects;
create policy "anon upload proof"
  on storage.objects
  for insert
  to anon
  with check (bucket_id = 'proof-of-purchase');

drop policy if exists "auth read proof" on storage.objects;
create policy "auth read proof"
  on storage.objects
  for select
  to authenticated
  using (bucket_id = 'proof-of-purchase');
