#!/usr/bin/env python3
"""
mobile_menu.py — the single source of truth for the phone menu drawer.

The site has no templating, so the drawer markup lives in every page. Edit the
MENU structure below and re-run this script; it stamps the same drawer (with
the right relative paths) into every active page, adds the drawer CSS + JS once
per page, and leaves everything else alone. Re-running is safe.

    python3 mobile_menu.py            # rewrite every page
    python3 mobile_menu.py --check    # report which pages are out of date, exit 1 if any

The drawer mirrors the desktop header: Find a Dealer on top, then one
accordion per desktop dropdown (Trailers, Owners, Dealers, Company). Keep the
Parts & Warranty link pointing at the parts catalog — see CLAUDE.md §3/§6.
"""
import argparse, glob, os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PAGE_GLOBS = ["*.html", "Gooseneck/*.html", "Deckover/*.html", "Landscape/*.html",
              "dump-trailers/*.html", "tilt-equipment/*.html"]
SKIP = {"404.html"}

CTA = ("Find a Dealer", "find-a-dealer")

# (group label, panel id, default open?, [(label, href)])
# hrefs are root-relative without a leading slash; the script prefixes "../"
# for pages in subfolders. External links start with http.
MENU = [
    ("Trailers", "mmTrailers", True, [
        ("Gooseneck Flatbeds", "Gooseneck/gooseneck"),
        ("Dump Trailers", "dump-trailers/dump-trailers"),
        ("Tilt Deck Trailers", "tilt-equipment/tilt-equipment"),
        ("Deckover Equipment", "Deckover/deckover"),
        ("Landscape Trailers", "Landscape/landscape"),
    ]),
    ("Owners", "mmOwners", False, [
        ("User Manuals", "user-manuals"),
        ("Video Guides", "video-guides"),
        ("Register Your Trailer", "register"),
        ("VIN Replacement", "vin-replacement"),
        ("Warranty Policy", "warranty"),
        ("Parts &amp; Accessories", "parts"),
        ("Contact Support", "contact"),
    ]),
    ("Dealers", "mmDealers", False, [
        ("Dealer Portal", "dealer-portal"),
        ("Become a Dealer", "become-a-dealer"),
        ("Parts &amp; Warranty", "https://walton-parts-catalog.vercel.app"),
    ]),
    ("Company", "mmCompany", False, [
        ("About Walton", "about"),
        ("Careers", "careers"),
        ("Contact Us", "contact"),
    ]),
]

CSS_MARK = "Mobile menu v2 (generated by mobile_menu.py)"
CSS = f"""
  /* {CSS_MARK} — edit mobile_menu.py, not this block */
  .mobile-menu {{ padding: 96px 24px 40px; }}
  .mobile-menu-cta {{ display: block; width: 100%; max-width: 420px; background: #b7a380; color: #f5f3ef !important; text-decoration: none; font-family: 'DM Sans', sans-serif; font-weight: 500; font-size: 15px; letter-spacing: 2px; text-transform: uppercase; text-align: center; padding: 17px 24px; border-radius: 2px; margin: 0 0 8px; }}
  .mobile-menu-group {{ width: 100%; max-width: 420px; border-bottom: 1px solid rgba(255,255,255,0.08); }}
  .mobile-menu-toggle {{ width: 100%; min-height: 64px; display: flex; align-items: center; justify-content: space-between; background: none; border: 0; padding: 14px 4px; font-family: 'Bebas Neue', sans-serif; font-size: 32px; letter-spacing: 3px; color: rgba(245,243,239,0.92); cursor: pointer; text-align: left; }}
  .mobile-menu-chevron {{ font-size: 16px; color: #b7a380; transition: transform 0.25s; }}
  .mobile-menu-group.open .mobile-menu-chevron {{ transform: rotate(180deg); }}
  .mobile-menu-panel {{ display: grid; grid-template-rows: 0fr; transition: grid-template-rows 0.28s ease; }}
  .mobile-menu-group.open .mobile-menu-panel {{ grid-template-rows: 1fr; }}
  .mobile-menu-panel > div {{ overflow: hidden; }}
  .mobile-menu-group.open .mobile-menu-panel > div {{ padding-bottom: 10px; }}
  .mobile-menu-panel a {{ display: flex; align-items: center; min-height: 48px; padding: 0 4px 0 16px; font-family: 'DM Sans', sans-serif; font-size: 17px; color: rgba(245,243,239,0.75); text-decoration: none; border-top: 1px solid rgba(255,255,255,0.05); }}
  .mobile-menu-panel a:hover, .mobile-menu-panel a:active {{ color: #f5f3ef; }}
  .hamburger.open span:nth-child(1) {{ transform: translateY(7px) rotate(45deg); }}
  .hamburger.open span:nth-child(2) {{ opacity: 0; }}
  .hamburger.open span:nth-child(3) {{ transform: translateY(-7px) rotate(-45deg); }}
  @media (prefers-reduced-motion: reduce) {{ .mobile-menu-panel, .mobile-menu-chevron {{ transition: none; }} }}
"""

JS_MARK = "function mmToggle"
JS = """
function mmToggle(btn) {
  var group = btn.parentNode;
  var open = !group.classList.contains('open');
  var groups = document.querySelectorAll('#mobileMenu .mobile-menu-group.open');
  for (var i = 0; i < groups.length; i++) {
    groups[i].classList.remove('open');
    groups[i].querySelector('.mobile-menu-toggle').setAttribute('aria-expanded', 'false');
  }
  group.classList.toggle('open', open);
  btn.setAttribute('aria-expanded', open ? 'true' : 'false');
}"""

BLOCK_RE = re.compile(r'<div class="mobile-menu" id="mobileMenu">[\s\S]*?\n</div>')
TOGGLE_RE = re.compile(r"function toggleMenu\(\) \{[\s\S]*?\n\}")
OLD_CSS_RES = [
    re.compile(r"^[ \t]*\.mobile-menu-link[^\n]*\n", re.M),            # inner pages
    re.compile(r"^[ \t]*\.mobile-menu-close \{[^\n]*\n", re.M),        # inner pages (base rule)
    re.compile(r"^[ \t]*\.mobile-menu-close \{ position: sticky[^\n]*\n", re.M),  # round-1 sticky rule
    re.compile(r"^[ \t]*\.mobile-menu-item[^{]*\{[\s\S]*?\}\n", re.M),  # index (multi-line + one-liners)
    re.compile(r"^[ \t]*\.mobile-menu\.open \.mobile-menu-item[^\n]*\n", re.M),
    re.compile(r"^[ \t]*\.mobile-menu-cta[^{]*\{[\s\S]*?\}\n", re.M),   # index cta rules (replaced by the block above)
]


def pages():
    out = []
    for g in PAGE_GLOBS:
        out += sorted(glob.glob(os.path.join(ROOT, g)))
    return [os.path.relpath(p, ROOT) for p in out if os.path.basename(p) not in SKIP]


def href(prefix, h):
    return h if h.startswith("http") else prefix + h


def link(prefix, label, h):
    ext = ' target="_blank" rel="noopener noreferrer"' if h.startswith("http") else ""
    return f'        <a href="{href(prefix, h)}"{ext}>{label}</a>'


def markup(prefix):
    lines = ['<div class="mobile-menu" id="mobileMenu">',
             '  <!-- generated by mobile_menu.py — edit MENU there, not here -->',
             f'  <a href="{href(prefix, CTA[1])}" class="mobile-menu-cta">{CTA[0]} &rarr;</a>']
    for label, pid, open_, items in MENU:
        cls = "mobile-menu-group open" if open_ else "mobile-menu-group"
        exp = "true" if open_ else "false"
        lines += [f'  <div class="{cls}">',
                  f'    <button class="mobile-menu-toggle" type="button" aria-expanded="{exp}" aria-controls="{pid}" onclick="mmToggle(this)">{label} <span class="mobile-menu-chevron" aria-hidden="true">&#9662;</span></button>',
                  f'    <div class="mobile-menu-panel" id="{pid}">',
                  '      <div>']
        lines += [link(prefix, l, h) for l, h in items]
        lines += ['      </div>', '    </div>', '  </div>']
    lines.append('</div>')
    return "\n".join(lines)


def render(page, html):
    prefix = "../" if os.sep in page or "/" in page else ""
    new = html
    if not BLOCK_RE.search(new):
        raise RuntimeError(f"{page}: mobile menu block not found")
    new = BLOCK_RE.sub(lambda m: markup(prefix), new, count=1)
    if CSS_MARK not in new:
        for rx in OLD_CSS_RES:
            new = rx.sub("", new)
        if "</style>" not in new:
            raise RuntimeError(f"{page}: no </style>")
        new = new.replace("</style>", CSS + "</style>", 1)
    if JS_MARK not in new:
        m = TOGGLE_RE.search(new)
        if not m:
            raise RuntimeError(f"{page}: toggleMenu() not found")
        new = new[:m.end()] + JS + new[m.end():]
    return new


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    stale = []
    for page in pages():
        fn = os.path.join(ROOT, page)
        html = open(fn, encoding="utf-8").read()
        new = render(page, html)
        if new != html:
            stale.append(page)
            if not args.check:
                open(fn, "w", encoding="utf-8").write(new)
    if args.check:
        print(f"{len(stale)} page(s) out of date" + (": " + ", ".join(stale) if stale else ""))
        sys.exit(1 if stale else 0)
    print(f"{len(stale)} page(s) rewritten, {len(pages()) - len(stale)} already current")


if __name__ == "__main__":
    main()
